# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6521, 0.5004, 0.6050],
        [0.9521, 0.5180, 0.2089],
        [0.9026, 0.8699, 0.9181],
        [0.2218, 0.7563, 0.4928],
        [0.2156, 0.3408, 0.5886]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [5]:
x[1:3] = 2
print(x)

tensor([[0.6521, 0.5004, 0.6050],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.2218, 0.7563, 0.4928],
        [0.2156, 0.3408, 0.5886]])


# Assignment

1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [6]:
x = torch.Tensor(2,17)
print(x.size())

torch.Size([2, 17])


In [7]:
x = torch.FloatTensor(3,1)
print(x.size())


torch.Size([3, 1])


In [8]:
x = torch.LongTensor(5,2,1)
print(x.size())

x[:]=7
print(x)

torch.Size([5, 2, 1])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [12]:
x = torch.ByteTensor(5,)
x[1:-1]=1
print(x)

tensor([208,   1,   1,   1,   0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [14]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)

tensor([[0.8083, 0.1590, 1.2307],
        [1.3694, 0.6322, 0.9824],
        [1.0789, 1.7432, 1.0360],
        [1.4646, 1.3731, 1.4294],
        [0.4264, 1.5110, 1.5130]])


### 2.2 Addition: syntax 2

In [15]:
print(torch.add(x, y))

tensor([[0.8083, 0.1590, 1.2307],
        [1.3694, 0.6322, 0.9824],
        [1.0789, 1.7432, 1.0360],
        [1.4646, 1.3731, 1.4294],
        [0.4264, 1.5110, 1.5130]])


### 2.3 Addition: giving an output tensor

In [16]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.8083, 0.1590, 1.2307],
        [1.3694, 0.6322, 0.9824],
        [1.0789, 1.7432, 1.0360],
        [1.4646, 1.3731, 1.4294],
        [0.4264, 1.5110, 1.5130]])


### 2.4 Addition: in-place

adds `x`to `y`

In [17]:
y.add_(x)
print(y)

tensor([[0.8083, 0.1590, 1.2307],
        [1.3694, 0.6322, 0.9824],
        [1.0789, 1.7432, 1.0360],
        [1.4646, 1.3731, 1.4294],
        [0.4264, 1.5110, 1.5130]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [18]:
print(x[:, 1])

tensor([0.0519, 0.2962, 0.8754, 0.5636, 0.6974])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiply of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

## 1:


In [20]:
z = x.mul(y)
print(z)

tensor([[0.5071, 0.0083, 1.1031],
        [1.2216, 0.1873, 0.8118],
        [0.1420, 1.5260, 0.6541],
        [0.7352, 0.7738, 1.2380],
        [0.0246, 1.0538, 0.8564]])


## 2:

In [21]:
x.mul_(y)
print(x)

tensor([[0.5071, 0.0083, 1.1031],
        [1.2216, 0.1873, 0.8118],
        [0.1420, 1.5260, 0.6541],
        [0.7352, 0.7738, 1.2380],
        [0.0246, 1.0538, 0.8564]])


## 3:

In [22]:
z = x.div(y)
print(z)

tensor([[0.6273, 0.0519, 0.8963],
        [0.8921, 0.2962, 0.8264],
        [0.1316, 0.8754, 0.6314],
        [0.5020, 0.5636, 0.8661],
        [0.0578, 0.6974, 0.5660]])


In [23]:
x.div_(y)
print(x)

tensor([[0.6273, 0.0519, 0.8963],
        [0.8921, 0.2962, 0.8264],
        [0.1316, 0.8754, 0.6314],
        [0.5020, 0.5636, 0.8661],
        [0.0578, 0.6974, 0.5660]])


## 4:

In [18]:
x = torch.rand(2,4)
y = torch.rand(2,4)
z = x.mul(y)
print(z)

tensor([[0.0804, 0.2876, 0.0498, 0.1313],
        [0.6965, 0.0573, 0.2903, 0.0945]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [31]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [32]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [33]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [34]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

## 1:

In [19]:
#Create tensor
x = torch.ones(5,2)
#Convert to numpy
x_np = x.numpy()
#Convert back from numpy to tensor
x_tensor = torch.from_numpy(x_np)

print(x)
print(x_np)
print(x_tensor)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [ ]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machie.")